apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: devops
  region: us-west-2

nodeGroups:
  - name: ng1
    instanceType: m5.large
    amiFamily: AmazonLinux2
    desiredCapacity: 2
    volumeSize: 80
    ssh:
      allow: true
      publicKeyName: KeyPair_Demo 

